services:
  - type: web
    name: land-registry-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: CONTRACT_ADDRESS
        sync: false
      - key: RPC_URL
        sync: false
      - key: PORT
        value: "3001"
      - key: PINATA_JWT
        sync: false
      - key: PINATA_GATEWAY
        value: https://gateway.pinata.cloud

  - type: web
    name: land-registry-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    plan: free
    envVars:
      - key: REACT_APP_CONTRACT_ADDRESS
        sync: false
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: land-registry-backend
          property: url
